### ISSUE TITLE
changed prefix not functioning

### ISSUE THREAD

**Issue by galantra** [Arthur-Milchior/anki-relation#3]
works great with default setting.
I reconfigured the prefix:
`{
    "current tag prefix": "related::",
    "query relation name": false,
    "tag prefixes": [
        "related::"
    ]
}`
I intended to incorporate all the relation tags into a hierarchical tag.
I did restart anki.

Now, when I relate two notes, the tags created still have the prefix "relation_". I want "related::".

**Comment by galantra** [comment]
Nevermind, it's functioning perfectly today. Thank you for this great add-on!

**Comment by Arthur-Milchior** [comment]
The problem disappeared ? I didn't take a look at it yet

**Comment by galantra** [comment]
I had to conduct a database check for anki to recognize the tags with the new prefix.
