### ISSUE TITLE
Suggestion: Option to automatically add relation tag to Image Occlusion notes

### ISSUE THREAD

**Issue by galantra** [Arthur-Milchior/anki-relation#4]
The add-on is especially useful with Image Occlusion notes because each occlusion is always created as one separate note. So, relation tags are an easy way to bury occlusion "siblings" that were created from the same image.

The process would be even easier if, when creating or editing an IO note, there was already an option to add a tag that includes the relation prefix followed by the card ID.

Alternative would be to do it manually. This would include looking up the ID after creation and pasting it. The relation shortcut does not work on notes with a single card.

I've also posted this suggestion in https://github.com/glutanimate/image-occlusion-enhanced/issues/111

**Comment by glutanimate** [comment]
Arthur, I've added an idea to the other discussion to do this via hooks in Image Occlusion (something like `runHook("ioNotesAdded", notes)`, which anki-relation could hook onto). Would that be something you'd be interested in supporting?

**Comment by Arthur-Milchior** [comment]
That's ok for me. Let me know when your add-on is updated, and what is the exact name of your hook

**Comment by galantra** [comment]
Anki's [native image occlusion](https://docs.ankiweb.net/editing.html?highlight=occlusion#image-occlusion) that was introduced a year ago actually creates the cards as siblings of a single note. Since newly introduced IO notes can be created via the native feature, the need for the relate notes add-on is no longer there. I'm closing the issue, and thanks for your contributions to Anki!
